### ISSUE TITLE
Stockfish exception in Chessbase

### ISSUE THREAD

**Issue by pmassie** [official-stockfish/Stockfish#2037]
I am seeing frequent exceptions when using Stockfish development versions to analyze in Chessbase 15.  The January 4 version was fine, but starting with the January 6 version and on until today when I use Stockfish for analysis Chessbase periodically reports "Stockfish has caused an exception.  This is a problem in the engine".  It seems to be related in some fashion to king safety, since it appears frequently in positions where kings are (or soon will be) somewhat exposed.  It appears anywhere from depth 21 to 35.  Both the development Stockfish and Brainfish show the same behavior.

**Comment by MichaelB7** [comment]
Interestingly, the patch introduced on January 6th has a line of code of code that was discussed here  #2036 .  
```
 Value singularBeta = std::max(ttValue - 2 * depth / ONE_PLY, -VALUE_MATE);
```
That specific line was fixed with this revert:
https://github.com/official-stockfish/Stockfish/commit/4d0981fef37c85edfd7a0e713d68a4542d7a6784

Can you grab or compiled a new version and see if the issue still exists?

**Comment by pmassie** [comment]
I was hopeful, but unfortunately I've already tested the latest and the problem still exists.  The latest I have is the Jan 10 version.  Chessbase error messages are not very descriptive, so all I can tell is the exception doesn't happen early in a game where lots of pieces are there, but once a king position starts to open up the exception starts to appear.  The Jan 4 version works fine.  The problem appears in the Jan 6 version, which I believe was the "Multi-cut" change.  My laptop is relatively new, with 16 GB of RAM and a six-core processor.  I've tried various hashtable sizes, various thread counts and pretty much everything else I can think of.  Nothing affects it.Paul


-------- Original Message --------
Subject: Re: [official-stockfish/Stockfish] Stockfish exception in
Chessbase (#2037)

**Comment by pmassie** [comment]
Apologies - there was a typo in my last message.  The latest I have is the March 10, not the January 10.

**Comment by MichaelB7** [comment]
Please post the fen or the pgn file where the crashed occurred.

**Comment by pmassie** [comment]
Here is a sample PGN.  Early in the game it generally seems fine, but when I put it on the last ply (move 27 as Black), it crashes pretty consistently.Paul[Event "?"][Site "?"][Date "2019.03.10"][Round "?"][White "Najdorf"][Black "?"][Result "*"][ECO "B91"][Annotator "rx"][PlyCount "54"][EventDate "2019.??.??"][SourceVersion "1"][SourceVersionDate "2014.04.15"][SourceQuality "1"]1. e4 c5 2. Nf3 d6 3. d4 cxd4 4. Nxd4 Nf6 5. Nc3 a6 6. g3 e5 7. Nb3 Be7 8. Bg2O-O 9. O-O Be6 10. a4 Nbd7 11. a5 Qc7 12. Re1 Rfc8 13. h3 h6 14. Be3 b5 15.axb6 Nxb6 16. Na5 Nc4 17. Nxc4 Bxc4 18. Na4 Rab8 19. b3 Bb5 20. c4 Bxa4 21.Rxa4 Qb7 22. Qa1 Qxb3 23. Rc1 Rc6 24. c5 Nd7 25. Rxa6 Rxa6 26. Qxa6 Nxc5 27.Bxc5 dxc5 $11 {1/2-1/2 (40) Leko,P (2740)-Topalov,V (2801) Wijk aan Zee 2006} *


-------- Original Message --------
Subject: Re: [official-stockfish/Stockfish] Stockfish exception in
Chessbase (#2037)

**Comment by MichaelB7** [comment]
I have been unable to replicate the crash on my machine. Take the current SF executable you are using and start stockfish in the command prompt.  ( for Windows, usually "stockfish.exe")

Then type the following commands in this order - you can copy paste:
```
uci
isready
setoption name threads value xx ( enter the number of threads you are using instead of xx)
setoption name hash value xxxx (enter the hash size your are using in MB instead of xxxx)
position fen 1r4k1/4bpp1/Q6p/2p1p3/4P3/1q4PP/5PB1/2R3K1 w - - 0 28
go infinite
```
and post the last 20 lines if it crashes ....

Also you can check your chessbase options to see if  you can turn logging or debug mode on... and repeat the process to get SF to  crash - that information may be useful ( it might be a bus error or segmentation fault) and post the log here.
Thanks.

**Comment by pmassie** [comment]
Very odd.  It doesn't crash when run under the command prompt.  I've spent time trying to find or figure out a way to turn on debugging under Chessbase, with no luck.I am rather confused on this - I'm not aware of anything really unique about my setup, so I don't see why it would be crashing for me and not others (or Cmd prompt).  Also, if this was a universal problem I'm sure many people would have reported it, which again suggests it's something unique.  On the other hand, the versions Jan 4 and before all work, which suggests it really is a Stockfish problem.  Yet it if is why isn't it showing under the Cmd prompt or with other people?It appears maybe Chessbase is more sensitive to something than are the other GUIs or the Cmd prompt.  I also tried it under Chessbase 14 with the same result, so it's not a new thing for Chessbase.I'm not sure where to go next...Paul


-------- Original Message --------
Subject: Re: [official-stockfish/Stockfish] Stockfish exception in
Chessbase (#2037)

**Comment by MichaelB7** [comment]
Since it seems to be a one off at this point , I suggest do a complete reinstall of the chessbase software. It’s easy for chessbase to say the engine exited with an error if there no logging facility.  Also check for any updates to the software you have.  Even with no logging facility with the chessbase software , there should be a logging option under the Stockfish engine options (unless chessbase hides it).  You have to point it to a log or text file , save the setting and see if you get a dump of what’s going on. My guess is that it is something in the communication between Stockfish and Chessbase that it is non standard. On that regard , Stockfish hasn’t been tweaked in that regard for months - so it could be a bad update from chessbase. If there was a wide spread problem , they would have a new update soon if not already.

**Comment by pmassie** [comment]
It does appear to be somewhat unique, so if I make any breakthroughs I'll let you know.  But in any case thanks for your help!

**Comment by MichaelB7** [comment]
ok - then, can you please close this issue . If you find anything else, you can always open a new  issue.  Thanks!

**Comment by pmassie** [comment]
FYI - It appears I have solved the problem, although I still don't understand why the results should be different between different versions of Stockfish.The problem is the SyzygyProbeLimit value.  By default it is set to 7, which fails on the more recent versions of Stockfish.  Setting it to a value of 5 or less prevents the exception from happening.  As it turns out, I have all the 5-man Syzygy tablebases and some of the 6-man, so it appears when it tries to hit a missing tablebase it's throwing an exception.  Curiously, the same default value of 7 is in place for the January 4 and before versions of SF, and those work fine.  Possibly something was changed in the way SF handles tablebases, but if so it wasn't documented anywhere I could find.Paul


-------- Original Message --------
Subject: RE: [official-stockfish/Stockfish] Stockfish exception in
Chessbase (#2037)
From: <pmassie@alar.com>
Date: Mon, March 11, 2019 6:39 pm
To: "official-stockfish/Stockfish"
<reply@reply.github.com>,
"official-stockfish/Stockfish" <Stockfish@noreply.github.com>
Cc: "Author" <author@noreply.github.com>

Very odd.  It doesn't crash when run under the command prompt.  I've spent time trying to find or figure out a way to turn on debugging under Chessbase, with no luck.I am rather confused on this - I'm not aware of anything really unique about my setup, so I don't see why it would be crashing for me and not others (or Cmd prompt).  Also, if this was a universal problem I'm sure many people would have reported it, which again suggests it's something unique.  On the other hand, the versions Jan 4 and before all work, which suggests it really is a Stockfish problem.  Yet it if is why isn't it showing under the Cmd prompt or with other people?It appears maybe Chessbase is more sensitive to something than are the other GUIs or the Cmd prompt.  I also tried it under Chessbase 14 with the same result, so it's not a new thing for Chessbase.I'm not sure where to go next...Paul   -------- Original Message -------- Subject: Re: [official-stockfish/Stockfish] Stockfish exception in Chessbase (#2037) From: Michael Byrne <notifications@github.com> Date: Sun, March 10, 2019 10:26 pm To: official-stockfish/Stockfish <Stockfish@noreply.github.com> Cc: pmassie <pmassie@alar.com>, Author <author@noreply.github.com>  I have been unable to replicate the crash on my machine. Take the current SF executable you are using and start stockfish in the command prompt. ( for Windows, usually "stockfish.exe") Then type the following commands in this order - you can copy paste: uci isready setoption name threads value xx ( enter the number of threads you are using instead of xx) setoption name hash value xxxx (enter the hash size your are using in MB instead of xxxx) position fen 1r4k1/4bpp1/Q6p/2p1p3/4P3/1q4PP/5PB1/2R3K1 w - - 0 28 go infinite  and post the last 20 lines if it crashes .... Also you can check your chessbase options to see if you can turn logging or debug mode on... and repeat the process to get SF to crash - that information may be useful ( it might be a bus error or segmentation fault) and post the log here. Thanks. —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by manuel0302** [comment]
I have this exception too, with Stockfish 14.

**Comment by rlsuth** [comment]
> 
> 
> I have this exception too, with Stockfish 14.

I have also just experienced this error with Stockfish 14 under Chessbase 15.

**Comment by vondele** [comment]
I'll reopen this as this affects multiple people, probably we need a debug log file showing exactly the sequence on commands sent to the engine. It might be related to having incomplete TB  sets ?

**Comment by rlsuth** [comment]
I'll try and get a log file next time it happens but after changing the TB probe limit to 5 it didn't happen again. I'll keep trying and see if I can replicate the issue.

**Comment by vondele** [comment]
I'll close this as we have no log file of this so far. If the issue happens again and a log file is available we can try to analyze.

**Comment by manuel0302** [comment]
This issue persists in SF16 with Chessbase 17.
