### ISSUE TITLE
Cornered Bishop Problem for NNUE in FRC

### ISSUE THREAD

**Issue by SFisGOD** [official-stockfish/Stockfish#3229]
Stockfish lost in an FRC game against Allie https://tcec-chess.com/#div=frc2fl&game=1&season=19

The problem is the cornered bishop on a1. Stockfish classical has the CorneredBishop penalty to deal with this problem.

I browsed in https://github.com/official-stockfish/books and there is no FRC book. It would be nice to have an FRC book as well @noobpwnftw for FRC testing

Also, almost lost against Minic here https://tcec-chess.com/#div=frc2la&game=13&season=19
Stockfish would have lost this game against a stronger opponent.

**Comment by vondele** [comment]
the classical eval has a corned bishop term added explicitly (as the only FRC term, IIRC).

**Comment by joergoster** [comment]
@SFisGOD See https://github.com/enedene/chess960-opening-book

**Comment by SFisGOD** [comment]
@vondele It would be nice to upload an FRC book to https://github.com/official-stockfish/books

**Comment by vondele** [comment]
@SFisGOD not so easy, since fishtest can't play FRC, needs changes to the framework to instruct cutechess to play variants

**Comment by Nordlandia** [comment]
This occurred in one of my FRC games. In the end Stockfish was essentially piece down and quickly lost. Its visually comparable to the snowball effect. By the way. The standard initial setup is one possible configuration within 960. So i would not call FRC a variant because  Chess960 encompasses Chess.

**Comment by vondele** [comment]
@Nordlandia it needs `-variant fischerandom ` to be passed to cutechess (for move validation and whatever).  So, right now it doesn't work out of the box. Also, consumers of fishtest games would need changes, since they don't expect variants. I would work out-of-the-box if we would remove all castling rights and just use the positions.

**Comment by ProteinGolem** [comment]
Has this issue has been recently addressed by a particular patch?

**Comment by vondele** [comment]
yes, at least practically, a term has been added to the NNUE eval that deals with this problem (gained about 40Elo for FRC). NNUE training is still not of on FRC games.

**Comment by vondele** [comment]
so, this is essentially fixed with the added term, will close the issue.
